# Generated by Django 3.2 on 2021-07-26 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jqrally_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EventSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('stamp_img', models.CharField(blank=True, max_length=256, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('mail', models.CharField(blank=True, max_length=256, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSpotPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=256, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.eventspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSpotComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.eventspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stamp', models.CharField(blank=True, max_length=2, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.eventspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.user')),
            ],
        ),
    ]
