# Generated by Django 3.2 on 2021-07-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jqrally_api', '0002_event_eventspot_eventuser_user_userspot_userspotcomment_userspotphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspot',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userspotcomment',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userspotphoto',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.event'),
            preserve_default=False,
        ),
    ]
