# Generated by Django 3.2 on 2021-07-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jqrally_api', '0004_eventspot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_img',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='eventspot',
            name='spot_img',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
