# Generated by Django 3.2 on 2021-07-31 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jqrally_api', '0005_auto_20210731_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_user',
            field=models.ForeignKey(default='6e0af7a3-6f1b-417c-9718-ea6799836db6', on_delete=django.db.models.deletion.PROTECT, to='jqrally_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
