# Generated by Django 3.2 on 2021-07-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jqrally_api', '0006_auto_20210731_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='disp_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='disp_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
