# Generated by Django 3.2 on 2021-08-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jqrally_api', '0008_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspot',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
