# Generated by Django 3.2 on 2021-08-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jqrally_api', '0009_eventspot_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspotphoto',
            name='photo',
            field=models.FileField(null=True, upload_to='', verbose_name='画像'),
        ),
    ]
